# Use this in your UnturnedImages/config.yaml file
- Id: "19000-19050" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3391808554/vehicles/{ItemId}.png" # The repository of the override.