# Use this in your UnturnedImages/config.yaml file
- Id: "49998-50057;50100-50121" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3546242167/vehicles/{ItemId}.png" # The repository of the override.